import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sofachromeItalic = localFont({
  src: "./fonts/Sofachrome-RgIt.otf",
  variable: "--font-sofachrome-italic",
  display: "swap",
});

const sofachromeRegular = localFont({
  src: "./fonts/Sofachrome-Rg.otf",
  variable: "--font-sofachrome-regular",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${sofachromeItalic.variable} ${sofachromeRegular.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
